### PR TITLE
NEP: Stack Isolation for NeoVM

### PR DESCRIPTION
**Pull request by erikzhang**
This NEP proposes that stack isolation of the NeoVM evaluation stack should be carried out to ensure the security of dynamic invocations and provide support for future new features.

### CODE REVIEW

**Comment by shargon** [comment]
`CALL` and `APPCALL` should copy all values but working on isolated way too, or this opCodes should not 
 be modified ?
Nodes shoud reject any new contract with old OpCodes on deploy? (how deal with this)
Are defined the new OpCode values?

**Comment by shargon** [comment]
0xB**X** have a hole
What do you think?

```
CALL_I = 0xB0,
CALL_E = 0xB1,
CALL_ED = 0xB2,
CALL_ET = 0xB3,
CALL_EDT = 0xB4
```

**Comment by erikzhang** [comment]
0xBX is OK.

**Comment by shargon** [comment]
In witch branch are `DYNAMICCALL` implemented? @localhuman

**Comment by localhuman** [comment]
In master.  We got rid of `DYNAMICCALL` opcode  and use `APPCALL` instead.

**Comment by shargon** [comment]
Then if there are not `DYNAMICCALL` OpCode why need `CALL_ED` and `CALL_EDT`. Is not the same?

**Comment by localhuman** [comment]
Does this relate to an issue of an `APPCALL` overwriting the `altstack` of the method it is being called within?

**Comment by erikzhang** [comment]
@localhuman Since we don't have `DYNAMICCALL`, can you edit NEP-4 to correct it?

**Comment by hal0x2328** [comment]
This change is urgently needed in order to safely do dynamic calls to untrusted contracts, and the AltStack needs to be isolated as well, as that is where contract global/local variables are stored. Very often `StorageContext` is saved in a named variable at the beginning of a contract, which could lead to any number of cross-contract security issues.

**Comment by valdor27** [comment]
Is someone other than Erik even working on NEO. No one seems to pay any heed to this PR

**Comment by erikzhang** [comment]
> Is someone other than Erik even working on NEO. No one seems to pay any heed to this PR.

Be patient, I'm working on it.

**Comment by erikzhang** [comment]
You can check the progress of the development for NEP-8 in this branch: https://github.com/neo-project/neo-vm/tree/feature/nep-8

**Comment by dicarlo2** [comment]
> On the other hand, some features, such as exception handling, also require stack isolation to be implemented.

Will exception handling be addressed in NEP-8 or another NEP?

**Comment by erikzhang** [comment]
> Will exception handling be addressed in NEP-8 or another NEP?

It's not in NEP-8.

**Comment by dicarlo2** [comment]
@erikzhang what's the status of this NEP? When will it be live?

**Comment by erikzhang** [comment]
The implementation has been completed. But it has not been deployed to the mainnet.

**Comment by dicarlo2** [comment]
@erikzhang do you have an estimate of when this will be deployed? I'm really looking forward to using this feature.

**Comment by erikzhang** [comment]
If all goes well, it will be deployed to the testnet next week.

**Comment by dicarlo2** [comment]
@erikzhang Great news! We've already updated neo-one to support stack isolation, and actually require it for the typescript compiler, so the sooner the better :)

**Comment by ixje** [comment]
FYI; `neo-python` and `neo-boa` now also have support for NEP8

**Pull request merged**
