### PR TITLE
NEP Dynamic Invoke

### PR DESCRIPTION
**Pull request by localhuman**
This NEP Proposal outlines a mechanism whereby a Smart Contract is provided the ability to invoke other Smart Contracts not known until runtime, rather than being limited to invoking only Smart Contracts that are defined at compile time. In order to retain the ability for Smart Contracts to interface with a future Dynamic Sharding process, included is a proposed specification to be used in the creation of Smart Contracts to denote whether a Smart Contract needs the Dynamic Contract Invocation feature or not.

### CODE REVIEW

**Comment by erikzhang** [comment]
Does dynamic invocation cost more fees?

**Comment by localhuman** [comment]
It is my opinion that using the `DYNAMICCALL` should cost more than `APPCALL` or `TAILCALL`.  I also believe that publishing an SC with the `HasDynamicInvoke` should cost more than publishing one without that feature.

**Comment by erikzhang** [comment]
So should SC with `HasStorage` cost more than SC without `HasStorage`?

**Comment by localhuman** [comment]
I think that would make sense.

**Comment by erikzhang** [comment]
What about this:
1. Every contract that be deployed costs 100 gas, this is the basic cost.
1. If it has a `HasStorage` flag, the cost is increased by 400 gas.
1. If it has a `HasDynamicInvoke` flag, the cost is increased by 500 gas.

**Comment by localhuman** [comment]
That sounds about right. I will update the proposal with those figures.

**Comment by localhuman** [comment]
Updated the fee structure, and removed the section of code demonstrating that the cost of a `DYNAMICCALL` would cost more than an `APPCALL`.

**Comment by erikzhang** [comment]
perfect

**Comment by localhuman** [comment]
I've updated the NEP number in the proposal to 4 🎉 
Is it ok to begin implementation?

**Comment by erikzhang** [comment]
Yes, let's do it!

**Comment by erikzhang** [comment]
@localhuman Since we don't have an opcode `DYNAMICCALL`, can you edit the NEP to correct it?

**Comment by localhuman** [comment]
Yes, will do!

**Pull request merged**
