### PR TITLE
NEP: Composite Smart Contracts

### PR DESCRIPTION
**Pull request by mwherman2000**
Close: #40

### CODE REVIEW

**Comment by erikzhang** [comment]
In order to implement this proposal, we need to remove all the optional methods of [NEP-5](https://github.com/neo-project/proposals/blob/master/nep-5.mediawiki).

**Comment by mwherman2000** [comment]
@erikzhang The optional operations/methods in NEP-5 have been removed and this PR has been updated.

**Comment by erikzhang** [comment]
@lllwvlvwlll Can you review the NEP-5 changes?

**Comment by erikzhang** [comment]
NEP-5 contracts can check the `payable` flag of the receiver contracts to decide whether it should transfer the tokens to those contracts.

https://github.com/neo-project/neo/blob/cb3a4a75854bb218b7b085b7b8bdaff0c69d7e8c/neo/Core/ContractPropertyState.cs#L6-L13

**Comment by mwherman2000** [comment]
@erikzhang Are you suggesting/requesting this as an addition to updated NEP-5? ...I can do that.  Let me know.

**Comment by erikzhang** [comment]
> Are you suggesting/requesting this as an addition to updated NEP-5? ...I can do that. Let me know.

Yes, please.

**Comment by erikzhang** [comment]
I think it's perfact now.

**Comment by lllwvlvwlll** [comment]
@erikzhang Can you provide some insight into what the payable flag is meant to do and whether it will support 'retroactive continuity' ?

**Comment by erikzhang** [comment]
After this PR is merged, I will propose a modification proposal to NEP-5, so that it can standardize the implementation details of each method. It will explain how the contract should deal with the `payable` flag during the transfer.

**Pull request merged**
