### PR TITLE
提出 NEOVM Dump 文件格式标准

### PR DESCRIPTION
**Pull request by lightszero**
提出NeoVM Dump文件格式标准
对NeoVM每一次 AppEngine.Run 进行逐个OpCode 和计算栈的Dump
则可以开发出回放合约工具，再加上map文件标准，回放工具就可以对应到合约源代码。
即可进行回放现场调试

### CODE REVIEW

**Comment by erikzhang** [comment]
Needs to translate into English.

**Comment by Robinfang000** [comment]
[PullRequest49-translated.docx](https://github.com/neo-project/proposals/files/2070627/PullRequest49-translated.docx)

**Comment by erikzhang** [comment]
@lightszero Can you provide an English version?

**Comment by steven1227** [comment]
@erikzhang @lightszero  English version is [here](https://github.com/Robinfang000/translation/blob/master/NeoVMDump-translated.mediawiki). But may need a little format and then replace this CN version

**Comment by erikzhang** [comment]
@lightszero Is this PR still updated?

**Comment by roman-khimov** [comment]
1. Outdated (Legacy)
2. Unmaintained.

Let's close it.

**Pull request closed without merging**
