### PR TITLE
Debug Info NEP

### PR DESCRIPTION
**Pull request by devhawk**

### CODE REVIEW

**Comment by devhawk** [comment]
This NEP has been accepted and it's ready to merge. I'm working on v2 of this format as part of [Storage Schema](https://github.com/neo-project/neo-debugger/blob/master/docs/storage-schema-overview.md) so it would be useful for me to get v1 merged ASAP.

Not sure who has review/commit privileges, so ccing some folks who've committed to this repo: @erikzhang @shargon @roman-khimov @superboyiii @bettybao1209

**Comment by devhawk** [comment]
ping @erikzhang @shargon @roman-khimov @superboyiii @bettybao1209

**Comment by erikzhang** [comment]
> This NEP has been accepted and it's ready to merge. I'm working on v2 of this format as part of [Storage Schema](https://github.com/neo-project/neo-debugger/blob/master/docs/storage-schema-overview.md) so it would be useful for me to get v1 merged ASAP.

Why don't we just go straight to v2?

**Comment by devhawk** [comment]
> Why don't we just go straight to v2?

V2 isn't ready yet. I just put the debugger that parses v2 into preview a couple days ago. No other compiler beyond a fork of NCCS emits the V2 format yet. I don't feel comfortable finalizing that until there's at least two compilers generating it and it's out of preview. 

I can open a V2 draft PR as soon as V1 is merged.

**Comment by devhawk** [comment]
Ping @erikzhang

**Comment by erikzhang** [comment]
@devhawk Can you convert the *.md file to *.mediawiki? Because GitHub won't generate `Table of Contents` for .md files automatically.

**Comment by devhawk** [comment]
> @devhawk Can you convert the *.md file to *.mediawiki? Because GitHub won't generate `Table of Contents` for .md files automatically.

Done

**Review by erikzhang — APPROVED** [review]

**Review by erikzhang — APPROVED** [review]

**Comment by devhawk** [comment]
I don't have merge rights

**Pull request merged**
