### PR TITLE
Mintable/Burnable NEP-5 Token

### PR DESCRIPTION
**Pull request by zlumer**
A NEP describing mintable/burnable NEP-5 compatible token.

Key points for discussion:
1. Should zero value mints/burns fire the corresponding event?
2. Should mint method be part of this specification or it's implementation can be left up to developer?

### CODE REVIEW

**Comment by erikzhang** [comment]
There is a description of the `transfer` event in [NEP-5](https://github.com/neo-project/proposals/blob/master/nep-5.mediawiki#transfer-1):

> A token contract which creates new tokens MUST trigger a transfer event with the from address set to null when tokens are created.
A token contract which burns tokens MUST trigger a transfer event with the to address set to null when tokens are burned.

So is it necessary to have `minted` and `burned`?

**Comment by zlumer** [comment]
Since this NEP assumes that we fully conform to NEP-5 spec, I guess we can omit the `minted` and `burned` events. In that case token mints can be found in tx list as `transfer` events from `null` address, and token burns are `transfer` events to `null` address in accordance with NEP-5. The wallets clients will have enough info to display them as mints/burns.

**Comment by saltyskip** [comment]
Minting and burning can have a much wider application compared to just an initial issuing. It also enables a coin with dynamic supply. This can be applied in things like loyalty programs and tether assets

Here is an example of such a contract that makes use of minting and burning to create a dynamic supply token

https://github.com/O3Labs/Blockchain-Loyalty-Program

Given the scope of minting and burning, I believe that these should be seperated into distinct events, if this standard were to move forward

**Comment by corck** [comment]
Some tokens, like the one I work on, have not hardcap, so hardcap() describe what is returned if there is not hardcap. Could be `-1`

**Pull request closed without merging**
