### PR TITLE
NEP: NEO Name Service Standard

### PR DESCRIPTION
**Pull request by PhyrexTsai**
This NEP presents standard with a set of contracts and methods that make NEO Name Service possible.
NEO Name Service can benefit with wallets and clients by human-readable identity instead of hexadecimal number.

### CODE REVIEW

**Comment by erikzhang** [comment]
Why do we need a standard, not a separate service?

**Comment by PhyrexTsai** [comment]
For extensibility, NNS designed with a standard that means every service build top on the NNS should follow the rule of this spec

**Comment by saltyskip** [comment]
I too believe that this should be a separate service and not a standard. It is up to the designer of the name service on how it should be structured. This puts an unnecessary restriction on any service that is developer.

This proposal should be closed

**Comment by erikzhang** [comment]
It should be a separate service and not a standard.

**Pull request closed without merging**
