### PR TITLE
Amend NEP6 for NEO3

### PR DESCRIPTION
**Pull request by shargon**
Now the script it's in base 64 format

*Based in my conversation with guil from neow3j*

### CODE REVIEW

**Comment by erikzhang** [comment]
The address format should be changed too.

**Comment by ixje** [comment]
1) The implementation link to the NEP6Wallet.cs in this NEP is invalid 
2) Both linked implementations are now invalid due to this change

**Comment by shargon** [comment]
`NEP6Wallet.cs` from neo3? what it's wrong?

**Comment by ixje** [comment]
> `NEP6Wallet.cs` from neo3? what it's wrong?

1. The link gets a `404`. 
2. You're right on the latest implementation of `NEP6Wallet.cs` to correctly support it. Was watching at an old copy 😑

**Pull request merged**
