### PR TITLE
add stub for proposals

### PR DESCRIPTION
**Pull request by erikzhang**
NEP-2: Passphrase-protected private key
---------------------------------------
This NEP describes a method for encrypting and encoding a passphrase-protected private key record.

NEP-3: Wallet Standard
----------------------
This NEP designs a wallet standard that allows the wallet files to be shared between the various implementations of NEO.

NEP-4: URI Scheme
-----------------
This NEP describes a URI scheme for making NEO based payments. The difference between BIP-21 and NEP-4 is that, BIP-21 makes payments that using bitcoin itself, and NEP-4 makes payments that using any asset on NEO.

NEP-5: Token Standard
---------------------
This NEP describes standard functions a token contract can implement.

NEP-6: Superconductive Exchange
-------------------------------
This NEP describes a mechanism for NEO based decentralized exchange.

NEP-7: Dynamic Sharding
-----------------------
This NEP describes a sharding mechanism that allows contracts to be executed in parallel.

NEP-8: Compact Block Relay
--------------------------
Compact blocks on the wire as a way to save bandwidth for nodes on the P2P network.

NEP-9: Peer Authentication
--------------------------
This NEP describes a way for peers to authenticate to other peers to guarantee node ownership and/or allow peers to access additional or limited node services, without the possibility of fingerprinting.

NEP-10: Aggregate Signature
---------------------------
An aggregate signature scheme is a digital signature that supports aggregation: Given n signatures on n distinct messages from n distinct users, it is possible to aggregate all these signatures into a single short signature. This single signature (and the n original messages) will convince the verifier that the n users did indeed sign the n original messages.

NEP-11: SM2 Cryptography
------------------------
Implement the [SM2 Digital Signature Algorithm](http://www.oscca.gov.cn/UpFile/2010122214822692.pdf) for NEO.

NEP-12: Homomorphic Encryption
------------------------------
Homomorphic encryption is a form of encryption that allows computations to be carried out on ciphertext, thus generating an encrypted result which, when decrypted, matches the result of operations performed on the plaintext.

NEP-13: Zero-knowledge proof
----------------------------
In cryptography, a zero-knowledge proof or zero-knowledge protocol is a method by which one party (the prover) can prove to another party (the verifier) that a given statement is true, without conveying any information apart from the fact that the statement is indeed true.

NEP-14: Stealth Addresses
-------------------------
Stealth addresses are a way for a payer and a payee to have a private exchange of funds.

NEP-15: NeoID
-------------
Digital identity refers to the identity information of individuals, organizations, and other entities that exist in electronic form. The more mature digital identity system is based on the PKI (Public Key Infrastructure) X.509 standard. In NEO, we will implement a set of X.509 compatible digital identity standards. This set of digital identity standards, in addition to compatible X.509 level certificate issuance model, will also support Web Of Trust point-to-point certificate issuance model. Our verification of identity when issuing or using digital identities includes the use of facial features, fingerprint, voice, SMS and other multi-factor authentication methods. At the same time, we will also use the blockchain to replace the Online Certificate Status Protocol (OCSP) to manage and record the X.509 Certificate Revocation List (CRL).

NEP-16: NeoFS
-------------
NeoFS is a distributed storage protocol that utilizes Distributed Hash Table technology. NeoFS indexes the data through file content (Hash) rather than file path (URI). Large files will be divided into fixed-size data blocks that are distributed and stored in many different nodes.

NEP-17: NeoX
------------
NeoX is a protocol that implements cross-chain interoperability. NeoX is divided into two parts: "cross-chain asset exchange protocol" and "cross-chain distributed transaction protocol."

NEP-18: NeoQS
-------------
NeoQS (Quantum Safe) is a lattice-based cryptographic mechanism. At present, quantum computers do not have the ability to quickly solve the Shortest Vector Problem (SVP) and the Closest Vector Problem (CVP), which is considered to be the most reliable algorithm for resisting quantum computers.

### CODE REVIEW

**Comment by lllwvlvwlll** [comment]
Fast Sync would also be one to add to the list. Maybe add a brief description for each (1 sentence).

**Comment by canesin** [comment]
@lllwvlvwlll NEP-8 ?

**Comment by a7594li** [comment]
good job

**Comment by revett** [comment]
👍

**Pull request merged**
