### PR TITLE
NEP-LATEST Token Exchange Basic Extensions

### PR DESCRIPTION
**Pull request by mwherman2000**
==Abstract==

The NEP-LATEST proposal defines three (3) additional methods designed to extend the base level token
functionality found in NEP-5 to support the needs of third-party agents such as exchanges.  Specialized exchanges
may require additional or different functionality.  They should create and submit additional NEP proposals that support their needs

### CODE REVIEW

**Comment by mwherman2000** [comment]
There's small issue with the formatting of a few characters like ", [ and ] ...maybe a character set issue.  I don't have time to look at this any more this morning.

**Comment by mwherman2000** [comment]
@erikzhang  Can you assign a reviewer/approver?  Thank you

@anfn101 @lllwvlvwlll @birmas

**Comment by erikzhang** [comment]
The extension can be accepted. However, it is likely to be discarded in NEO 3.0, as there are plans to add multiple APIs to implement this extension's functionalities.

**Comment by birmas** [comment]
If that's the case then nep5 should have been left as is to begin with and the need for these temporary, useless, neps wouldn't be needed.

My mainnet contract will not support "nep-latest" it will continue to support the previously "final" version of nep5

**Comment by erikzhang** [comment]
@birmas For contracts, what's the difference?

**Comment by birmas** [comment]
@erikzhang the difference is the manner this NEP-LATEST is proposed. 

* By retrospectively modifying the "final" NEP5 which projects have used and deployed to mainnet. 
* By closing down this perfectly acceptable (and complete!) proposal for NEP-51? https://github.com/neo-project/proposals/issues/59

When I said I will not support NEP-LATEST in my contract I mean: the response I give for NEP-10 supportedStandards() will not include NEP-LATEST. It will continue to return NEP-5 and NEP-10.

**Comment by erikzhang** [comment]
The proposals #58 and #59 want to create a new token standard that includes NEP-5 and optional methods. Once this standard is used, the NEP-5 will be discarded.
But in https://github.com/neo-project/proposals/pull/61#issuecomment-407069002 we have learned that a large number of old contracts have already supported the NEP-5 standard, so it cannot be discarded.
This proposal create an extension to NEP-5. This will preserve the compatibility of the old contracts. And when the NEO 3.0 is online, we can easily discard this proposal, leaving only the NEP-5 part.
So it has nothing to do with manner, I only choose from a technical point of view.

**Comment by birmas** [comment]
That makes sense but then why not just leave nep5 as it was in its final version?

This whole situation is because the"final' standard was retrospectively modified?

**Comment by birmas** [comment]
"The extension can be accepted. However, it is likely to be discarded in NEO 3.0, as there are plans to add multiple APIs to implement this extension's functionalities."

As you said, it seems like this whole process was something that's going to result in it being discarded anyway.

The amount of time and the division this "change process" has caused in the community is shocking.

**Comment by decentralisedkev** [comment]
@erikzhang If we added a new NEP that was seen as an improvement on NEP5 and a full token standard, then we can still support the older contracts, while telling new contracts to implement the newer standard instead.

I don't think we should have went back and edited NEP5, if NEP10 was incompatible with optional methods, it would have been better to create a new token standard that was compatible with it or not implement NEP10.

**Comment by ThomasLobker** [comment]
These methods are not limited to exchanges and they can in fact be very useful in many cases (handling in-dApp payments for example). I would recommend changing the title to _Allowance Extensions_. As mentioned [in my comment here](https://github.com/neo-project/proposals/pull/61#issuecomment-407069002) a couple of NEP-5 tokens are already compatible with these extensions, so in my opinion this is be a valuable proposal and it should be accepted.

**Comment by mwherman2000** [comment]
RE: I would recommend changing the title to Allowance Extensions

I, for one, am not stuck on the draft name.  However, I don't think "Allowance Extensions" is descriptive enough.  What is the precise, *collective* purpose of *allowance*, *transferFrom*, and *approve* methods? [I've deliberate phrasing this in a naive tone.]

How about something like "Token Extension: Third Party Transfers"? ...also think about this as a naming pattern for similar future extensions e.g. NFT, requisitions/remittance processing.

**Comment by mwherman2000** [comment]
RE: "The extension can be accepted. However, it is likely to be discarded in NEO 3.0, as there are plans to add multiple APIs to implement this extension's functionalities."

@erikzhang There has been no (open, public) discussion about NEP-5 being discarded in the future.  Can you explain? ...perhaps in a new issue/discussion if necessary.

**Comment by mwherman2000** [comment]
NEP-10 Documentation
```csharp
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;
using System;
using System.Numerics;

namespace NEO.NEP.Examples
{
    public class TokenExtensionThirdPartyTransfers : SmartContract
    {
        public static object Main(string operation, params object[] args)
        {
            object result = false;

            if (operation == "supportedStandards")
            {
                result = (object)supportedStandards();
            }
            else if (...)
            {
                ...
            }
            ...

            return result;
        }

        public static string[] supportedStandards()
        {
            string[] result = { "NEP-5", "NEP-10", "NEP-LATEST" };

            return result;
        }
    }
}
```

**Comment by RavenXce** [comment]
At the moment this is just a skeleton?

Details of exactly how the operations should work especially with regards to the unhappy paths / contentious cases (0 transfer amount, etc.), non-common cases (invoked from another contract, etc.) should be in the spec, lest the same mistakes that were made in the original NEP-5 are made again.

Also, these threads are important for user UX and programmer safety. The implementation we want to use + the caveats we're willing to accept should be clear:
https://github.com/ethereum/EIPs/issues/738
https://github.com/CORIONplatform/solidity/issues/107

**Comment by mwherman2000** [comment]
@erikzhang Is it possible to move this PR forward - at least to the point where its given a number?  
If not, what is holding this up (besides the recent events on the NEO blockchain)?

**Comment by erikzhang** [comment]
> Details of exactly how the operations should work especially with regards to the unhappy paths / contentious cases (0 transfer amount, etc.), non-common cases (invoked from another contract, etc.) should be in the spec, lest the same mistakes that were made in the original NEP-5 are made again.

I think that this proposal must be clearly stated before it is accepted.

**Pull request closed without merging**
