### PR TITLE
NEP: Non fungible tokens with expirable transfer

### PR DESCRIPTION
**Pull request by quelibrio**
to be reviewed and improved

### CODE REVIEW

**Comment by erikzhang** [comment]
@neo-project/everyone I modified the title. We should discuss this proposal.

**Comment by quelibrio** [comment]
cool i'll write you to elaborate things

**Comment by vncoelho** [comment]
@erikzhang, do you prefer this as a specially contract functionality implemented by a thirdy party?

**Comment by erikzhang** [comment]
Yes.

**Comment by quelibrio** [comment]
Guys don't delete pull request please. We didn't implement this to the end because we found one flaw in the concept. Each time we calculate if the token has to be returned we call the smart contract which manages those assess and that costs additional gas. If we do that too often its a too expensive operation. But if the person who wants tokes returned invokes the contract its more effective. However its a bit strange scenario. We consider reimplementing this in python.

**Pull request closed without merging**
